### ISSUE TITLE
Mark Posts ToDo List

### ISSUE THREAD

**Issue by hofmannsven** [flymke/mark-posts#19]
- [ ] Testing with PHPUnit
- [ ] Delete all Markers option
- [x] Show drafts on dashboard
- [ ] Disable colors
- [x] Import/Export Markers

**Comment by markjcasey** [comment]
Hey

Great plugin.

Would it be possible to set specific roles to use markers? So, for example, an editor could use all the markers but a contributor could only use the ones they have permission to use.

This would be really useful as contributors could update their posts and mark them as 'Updated' but not use any of the admin markers such as 'Rejected - too short'.

Thanks :)

**Comment by flymke** [comment]
Hi Mark,

Thanks for your feedback! Setting roles would be great feature and certainly will be put on the Todo list. Thank you for sharing your idea and your feedback!

Happy easter!
Mike

**Comment by flymke** [comment]
- [x] Setting specific user roles (thanks Mark!)

**Comment by hofmannsven** [comment]
Setting specific user roles for specific markers will be possible with the next (v1.0.4) release of the plugin. We've implemented the filter `mark_posts_marker_limit`; please check the [Custom Marker Limits](https://github.com/flymke/mark-posts/wiki/Custom-Marker-Limits) wiki page for further information :)

**Comment by flymke** [comment]
Hi Mark,
We've just released v1.0.4. You should be able to update it through the WordPress dialogue :)
Mike

EDIT: v.1.0.5 is the current release. Thanks!

**Comment by markjcasey** [comment]
Awesome. Thanks, I'll give it a try soon.

**Comment by dgoze** [comment]
Would there be an easy way to add markers to the Media Library as well?  Would love to be able to mark images as "Too Small" or "Needs Alt Tag".

Also kind of like the idea of users able to make their own markers, but also let Admin change them if needed.

Thanks, it's a plugin that seems like it should already be part of WordPress!  It makes way more sense then trying to tell a user how to find an item they need to fix.

**Comment by cracki** [comment]
Hi
can we add 3 mark to one post?

**Comment by danfolt** [comment]
Hi,
any plans about frontend implementation? Would be very nice if we can use this plugin for example for a hotel website, "posts" are incoming "bookings" and receptionists can mark the bookings with their names after inserting the booking to the hotel system can mark them as "completed by Tom", "completed by Richard" etc. Thanks Daniel

**Comment by hofmannsven** [comment]
We migrated the GitHub repository to [hofmannsven/mark-posts](https://github.com/hofmannsven/mark-posts).
